# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 02:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('share', '0003_auto_20170203_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='otp',
            field=models.CharField(default=1234, max_length=6),
        ),
        migrations.AddField(
            model_name='signup',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='signup',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
