# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0004_auto_20170204_0244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='status',
            new_name='is_active',
        ),
    ]
